# Generated by Django 5.2.4 on 2026-07-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student__first_name']},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-start_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date_issued']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
