services:
  web:
    build: .
    ports: ["8000:8000"]
    environment:
      DEBUG: "True"
      SECRET_KEY: "django-insecure-docker-key"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    volumes: [".:/app"]
    command: sh -c "python manage.py migrate && gunicorn edutrack.wsgi:application --bind 0.0.0.0:8000"
